server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    # Neomezená velikost uploadu
    client_max_body_size 0;
    client_body_timeout 3600s;
    send_timeout 3600s;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_read_timeout 3600s;
        fastcgi_send_timeout 3600s;
        fastcgi_buffering off;
    }

    location ~ /\.ht {
        deny all;
    }
}
